workflows:
  flutter:
    name: Flutter Workflow
    instance_type: macos-xcode-11
    scripts:
      - echo "Building Flutter project"
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
